# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    command: python manage.py serve
    volumes:
      - .:/app
    ports:
      - 8001:8000

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/db
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
